// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpa4R8b6RFcAwAnZ1NrbJN4UKJZtg0DqY',
    appId: '1:124527389737:web:2461dc899c129b3045c038',
    messagingSenderId: '124527389737',
    projectId: 'embedded-project-4605a',
    authDomain: 'embedded-project-4605a.firebaseapp.com',
    storageBucket: 'embedded-project-4605a.firebasestorage.app',
    measurementId: 'G-0E0M5H0Q6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ0XklHCPe2YRveNjUynP6Yuvpfp7aX_8',
    appId: '1:124527389737:android:89d3c0f6024f58f345c038',
    messagingSenderId: '124527389737',
    projectId: 'embedded-project-4605a',
    storageBucket: 'embedded-project-4605a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlDSIRQ_UCs2sS1FHgqy1sD-kAuorMHdU',
    appId: '1:124527389737:ios:825b1c9f3937086545c038',
    messagingSenderId: '124527389737',
    projectId: 'embedded-project-4605a',
    storageBucket: 'embedded-project-4605a.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlDSIRQ_UCs2sS1FHgqy1sD-kAuorMHdU',
    appId: '1:124527389737:ios:825b1c9f3937086545c038',
    messagingSenderId: '124527389737',
    projectId: 'embedded-project-4605a',
    storageBucket: 'embedded-project-4605a.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpa4R8b6RFcAwAnZ1NrbJN4UKJZtg0DqY',
    appId: '1:124527389737:web:6e66d3f5e92d0ac145c038',
    messagingSenderId: '124527389737',
    projectId: 'embedded-project-4605a',
    authDomain: 'embedded-project-4605a.firebaseapp.com',
    storageBucket: 'embedded-project-4605a.firebasestorage.app',
    measurementId: 'G-WZ19H6999R',
  );
}
